import type { Metadata } from 'next'
import { Rentals } from '@/app/(private)/locacoes/_components/rentals'

export const metadata: Metadata = {
  title: 'Locações',
  description: 'Generated by create next app',
}

export default async function Page() {
  return <Rentals />
}
