import type { Metadata } from 'next'
import { Properties } from '@/app/(private)/dashboard/propriedades/_components/properties'

export const metadata: Metadata = {
  title: 'Propriedades',
  description: 'Generated by create next app',
}

export default async function Page() {
  return <Properties />
}
