import type { Metadata } from 'next'
import { RegisterProperties } from '@/app/(private)/imoveis/cadastrar/_components/register'

export const metadata: Metadata = {
  title: 'Imóveis | Cadastrar',
  description: 'Generated by create next app',
}

export default async function Page() {
  return <RegisterProperties />
}
