import type { Metadata } from 'next'
import { EditProperties } from '@/app/(private)/imoveis/editar/[id]/_compoenents/edit'

export const metadata: Metadata = {
  title: 'Imóveis | Editar',
  description: 'Generated by create next app',
}

export default async function Page() {
  return <EditProperties />
}
